### ISSUE TITLE
Question: activities aren't showing up

### ISSUE THREAD

**Issue by twomice** [JMAConsulting/biz.jmaconsulting.olarkchat#12]
Hi,

I've just set up a new Olark account and new CiviCRM testing site, set up the integration as described in the README, but activities aren't being created.

I tried these things, each of which I thought would create a chat activity in CiviCRM, but none did:

- I successfully established an olark chat session, and tried, from the olark.com dashboard, issuing the `!lead` command in the chat window.
- Ensured the webhook confg included the "Send all transcripts automatically" option, then closed the chat.
- Clicked the "test" link in the webhook configuration.
- Sent an HTTP post via curl, which yields no visible output:
```
$ curl -X POST --data-urlencode 'data={"kind": "Conversation", "tags": ["olark", "customer"], "items": [{"body": "Hi there. Need any help?", "timestamp": "1307116657.1", "kind": "MessageToVisitor", "nickname": "John", "operatorId": "1234"}, {"body": "Yes, please help me with billing.", "timestamp": "1307116661.25", "kind": "MessageToOperator", "nickname": "Bob"}], "operators": {"1234": {"username": "jdoe", "emailAddress": "john@example.com", "kind": "Operator", "nickname": "John", "id": "1234"}}, "groups": [{"kind": "Group", "name": "My Sales Group", "id": "0123456789abcdef"}], "visitor": {"ip": "123.4.56.78", "city": "Palo Alto", "kind": "Visitor", "conversationBeginPage": "http://www.example.com/path", "countryCode": "US", "country": "United State", "region": "CA", "chat_feedback": {"overall_chat": 5, "responsiveness": 5, "friendliness": 5, "knowledge": 5, "comments": "Very helpful, thanks"}, "operatingSystem": "Windows", "emailAddress": "bob@example.com", "organization": "Widgets Inc.", "phoneNumber": "(555) 555-5555", "fullName": "Bob Doe", "customFields": {"favoriteColor": "blue", "myInternalCustomerId": "12341234"}, "id": "9QRF9YWM5XW3ZSU7P9CGWRU89944341", "browser": "Chrome 12.1"}, "id": "EV695BI2930A6XMO32886MPT899443414"}' 	http://_REDACTED_/civicrm/olarkchat?snippet=4&olarksecret=_REDACTED_
$ 
```

My olark webhook settings look like this:
![olark-webhook](https://user-images.githubusercontent.com/759449/31787162-753845d0-b4d0-11e7-8cc5-d3da9137eb69.png)

Any suggestions?

**Comment by Edzelopez** [comment]
Hi @twomice,

There are two things which might have prevented the creation of the activity.
1. The callback URL should consist of only the olarksecret, so please remove snippet=4 so that the URL reads http://_REDACTED_/civicrm/olarkchat?olarksecret=_REDACTED_

2. The operator should have a pre-existing CiviCRM account since as of now, the extension does not support creation of a new operator. In this example, the operator is john@example.com, so please make sure a contact with that email exists in the system. 

I made these two changes on a new installation and the activity was created successfully when I accessed the callback URL with the POST data you provided.

![chat](https://user-images.githubusercontent.com/1990869/31877379-df3f0c54-b7f3-11e7-88c8-bc7e85346952.png)

Hope this helps!
Edsel

**Comment by twomice** [comment]
Thanks, @Edzelopez . As far as I can tell, the `snippet=4` part is fine to have in the URL. The main part was creating a CiviCRM contact with the same email address as the olark operator. Once that's done, the integration seems to work fine. 

Perhaps it's worth noting this in the README?

Thanks for your help.
